-- Міграція: додаємо поля для повного зберігання даних подорожей

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE,
  ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';

ALTER TABLE trips
  ADD COLUMN IF NOT EXISTS stops   JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS legs    JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS blocks  JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS days    JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS route   JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS photos  JSONB NOT NULL DEFAULT '[]';
